name: Send Update to Private Server Repo

on:
  push:
    branches:
      - main

jobs:
  update-private-repo:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Private Target Repository
        uses: actions/checkout@v4
        with:
          repository: Bestrust-Servers/Server-Files
          token: ${{ secrets.PRIVATE_REPO_TOKEN }}
          submodules: true

      - name: Update the Submodule Pointer
        run: |
          git submodule update --remote all_servers/oxide/lang

      - name: Commit and Push to Target Repo
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add all_servers/oxide/lang
          
          # This line prevents the Action from crashing if the pointer didn't actually change
          git diff --quiet && git diff --staged --quiet || (git commit -m "Updated translations submodule (https://github.com/Bestrust-Servers/Translations)" && git push origin main)
